### ISSUE TITLE
Any logged in user can send message to anyone else

### ISSUE THREAD

**Issue by SathyaBhat** [avinassh/della#10]
I am not sure if this is a bug or feature by default, but any logged in user can message any other user by simply replacing the username in the URL. This leads to situations like this:

![image](https://cloud.githubusercontent.com/assets/25424/21081082/06da489e-bfe5-11e6-95fe-0ddfc994beb9.png)

**Comment by avinassh** [comment]
Yes, anyone can send messages to anyone. But I don't understand how it could be a bug?

**Comment by SathyaBhat** [comment]
hence the qualifier.

> I am not sure if this is a bug or feature by default


Though I am not really sure what would be the use case for a general messaging system

**Comment by avinassh** [comment]
I thought it would be nice to have messaging. Comes handy if people don't have telegram groups like us, say when you are running this within your compnay for a set of 100-150 people.
