### ISSUE TITLE
Writing Unit tests

### ISSUE THREAD

**Issue by mish24** [avinassh/della#15]
This is a really cool application. I saw that in new features you mentioned tests. Would it be fine if you assign it to me? That way I'll get more insight to the packages used and code as well. @avinassh

**Comment by avinassh** [comment]
Yes! Sure, go ahead. Let me know if you need any help

**Comment by dumptyd** [comment]
Teach me django and how to write unit tests senpai.

**Comment by avinassh** [comment]
@dumptyd sure! 

1. Get Della running locally. Instructions on README.
2. Pick one Django App, smaller one and pick each functions/methods and then think of success and failure cases
3. Then... Start writing tests?
4. For inspiration, Nightreads has some tests - [here](https://github.com/avinassh/nightreads/blob/master/nightreads/user_manager/tests.py)

**Comment by anweshknayak** [comment]
@dumptyd you working on this ? :P
